# Generated by Django 5.0.7 on 2024-07-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Is manager'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile',
            field=models.BooleanField(default=False, verbose_name='Is franchise'),
        ),
    ]
