# Generated by Django 5.0.7 on 2024-07-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_manager_user_is_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_profile',
            field=models.BooleanField(default=False, verbose_name='Is profile'),
        ),
    ]
