# Generated by Django 5.1.4 on 2025-03-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_notification_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.CharField(choices=[('Students', 'Students'), ('Parents', 'Parents')], default='Parent', max_length=25),
        ),
    ]
