# Generated by Django 5.1.4 on 2025-03-25 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='washslot',
            options={'ordering': ['start_time'], 'verbose_name': 'wash slot', 'verbose_name_plural': 'wash slots'},
        ),
        migrations.RemoveField(
            model_name='washslot',
            name='date',
        ),
        migrations.AddField(
            model_name='washslot',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'is_student': True}, related_name='whash_slot', to=settings.AUTH_USER_MODEL),
        ),
    ]
