# Generated by Django 5.1.4 on 2025-03-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_foodmenu_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodmenu',
            options={'ordering': ['-id'], 'verbose_name': 'food menu', 'verbose_name_plural': 'food menus'},
        ),
        migrations.RemoveField(
            model_name='foodmenu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='foodmenu',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='breakfast',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='dinner',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='lunch',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='snack',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
